version: "3"

services:
  thread:
    image: cosmtrek/air
    container_name: thread_service
    working_dir: /app/thread/cmd
    depends_on:
      - thread_db
    ports:
      - "8080:8080"
    volumes:
      - .:/app
  thread_db:
    container_name: thread_db
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=thread
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5433:5432'
    volumes:
      - ./thread/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./thread_db:/var/lib/postgresql/data

