version: "3"

services:
  thread:
    image: cosmtrek/air
    working_dir: /app/thread/cmd
    restart: always
    depends_on:
      - thread_db
    ports:
      - "8080:8080"
    volumes:
      - .:/app
  thread_db:
    container_name: thread_db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=thread
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '9093:5432'
    volumes:
      - ./thread/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      -  thread_db:/var/lib/postgresql/data
  identification:
    image: cosmtrek/air
    working_dir: /app/identification/cmd
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    depends_on:
      - identification_db
  identification_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=identification
    ports:
      - "9092:5432"
    volumes:
      - identification_db:/var/lib/postgresql/data
  board:
    image: cosmtrek/air
    working_dir: /app/board/cmd
    depends_on:
      - board_db
    ports:
      - "8082:8082"
    volumes:
      - .:/app
  board_db:
    container_name: board_db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=board
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '9091:5432'
    volumes:
      - ./board/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - board_db:/var/lib/postgresql/data
  media:
    image: cosmtrek/air
    working_dir: /app/media/cmd
    ports:
      - "8083:8083"
    volumes:
      - .:/app
volumes:
  identification_db:
  thread_db:
  board_db:

