version: "3"

services:
  thread:
    image: cosmtrek/air
    working_dir: /app/thread/cmd
    depends_on:
      - thread_db
    ports:
      - "8080:8080"
    volumes:
      - .:/app
  thread_db:
    container_name: thread_db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=thread
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5433:5432'
    volumes:
      - ./thread/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      -  thread_db:/var/lib/postgresql/data
  identification:
    image: cosmtrek/air
    working_dir: /app/identification/cmd
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    depends_on:
      - identification_db
  identification_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=identification
    ports:
      - "5401:5432"
    volumes:
      - identification_db:/var/lib/postgresql/data
volumes:
  identification_db:
  thread_db:

